version: "3.8"

services:
  app:
    image: node:12-alpine
    command: sh -c "npm install && npm run"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: budgets

  postgres:
    image: postgres
    volumes:
      - pg-budget-data:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: secret
      POTGRES_DB: budgets

volumes:
  pg-budget-data:
