version: "3.9"

services:
  app:
    build: ./code
    image: budget-script
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./code:/app:Z
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    depends_on: 
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - 6000:5432
    volumes:
      - ./data/data.sql:/docker-entrypoint-initdb.d/data.sql:Z
    healthcheck:
      test: pg_isready -U postgres 
      interval: 1s
      timeout: 5s
      retries: 5
